# Generated by Django 6.0.5 on 2026-06-16 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField(unique=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('saldo', models.FloatField(default=200)),
                ('cartao_cadastrado', models.BooleanField(default=False)),
                ('numero_cartao', models.CharField(blank=True, max_length=16, null=True)),
                ('nome_cartao', models.CharField(blank=True, max_length=100, null=True)),
                ('validade_cartao', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
