# Generated by Django 6.0.5 on 2026-06-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('balance', models.FloatField(default=200)),
                ('card_registered', models.BooleanField(default=False)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('card_name', models.CharField(blank=True, max_length=100, null=True)),
                ('card_expiration', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
