# Generated by Django 6.0.5 on 2026-06-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField()),
                ('produto_id', models.IntegerField(null=True)),
                ('produto_nome', models.CharField(blank=True, max_length=100, null=True)),
                ('produto_preco', models.FloatField(null=True)),
                ('adicionais', models.TextField()),
                ('entrega', models.CharField(max_length=30)),
                ('pagamento', models.CharField(max_length=30)),
                ('subtotal', models.FloatField()),
                ('desconto', models.FloatField()),
                ('taxa_entrega', models.FloatField()),
                ('valor_total', models.FloatField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
