# Generated by Django 6.0.5 on 2026-05-14 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adicionais', models.TextField()),
                ('entrega', models.CharField(max_length=30)),
                ('pagamento', models.CharField(max_length=30)),
                ('subtotal', models.FloatField()),
                ('desconto', models.FloatField()),
                ('taxa_entrega', models.FloatField()),
                ('valor_total', models.FloatField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('produto_id', models.IntegerField(null=True)),
                ('produto_nome', models.CharField(max_length=100, null=True, blank=True)),
                ('produto_preco', models.FloatField(null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
